spring:
  profiles:
    include:
      - cpp
  application:
    name: app-tar-template

  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid: #  配置参考 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_DruidDataSource%E5%8F%82%E8%80%83%E9%85%8D%E7%BD%AE
      #监控统计拦截的filters
      filters: "stat,mergeStat"
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://mysql.3cgg.rec:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: jiazhongjin
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      connect-properties:
        "druid.stat.slowSqlMillis": 5000
      stat-view-servlet:  # 查看druid监控页面 http://localhost:8570/druid/index.html
        enabled: true
  aop:
    proxy-target-class: true


mybatis-plus:
  # xml
  mapper-locations: classpath:mapping/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.jianan.protocol.adcp
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    -ROOT: debug
  path: ${spring.application.name}
  file:  file:D:\J\git\app-tar-tempalte\src\main\resources\log4j2.xml

server:
  port: 7100

